---
- name: 'updating packages' # sudo apt upgrade
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86700
- name: remove dormant dependencies # sudo apt autoremove
  become: yes
  apt:
    autoremove: yes
    
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    # get ENV variables
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    - NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
    - TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    - TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    
- name: install dependencies  # sudo apt install nodejs npm
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
    
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
      
- name: Install pm2 # sudo npm install pm2 -g
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

  roles:
    # Your code here
    - configure-server