---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Copy backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app/artifact.tar.gz
    recursive: true
    
- name: "Unarchive backend files"
  shell: |
    cd ~/backend_app
    tar –xvzf artifact.tar.gz
    rm -rf artifact.tar.gz

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu